### ISSUE TITLE
Front matter sticky is not work

### ISSUE THREAD

**Issue by f-dong** [hexojs/hexo-generator-index#101]
### Check List

- [X] I have already read README.
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the latest version of this repository.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo.
- [X] My Node.js is matched the required version.

### Describe the bug

- [x] I've attempted to execute `hexo clean`, but the issue persists.

Here is an example of Front Matter
```md
sticky: 99
title: A simple test
date: 2022-07-24
tags:
- es
categories: es
updated: 2022-08-17
```

### Expected behavior

Articles with 'sticky' set are displayed at the top.

### How to reproduce

1. Install hexo
2. Modify a certain article to change 'sticky' to '999'.
3. Observe the order of articles by running `npm run server`.

### Environment information

```text
- System: Windows 11 (21H2)
- HEXO: 6.3.0
- hexo-generator-index: 3.0.0
- NODE: v20.9.0
- NPM: 10.1.0
```

**Comment by stevenjoezhang** [comment]
My tests show that the sticky functionality is working fine. Could you create a repository with code that reproduces the issue? Thanks!
