### ISSUE TITLE
Add info about the index_generator to the official documentation

### ISSUE THREAD

**Issue by johot** [hexojs/hexo-generator-index#12]
I spent so many hours trying to find out how to have a `blog` section (instead of using index as the blog page) together with a regular static index page in my hexo generated website.

I then found out through github issues that I could add a:

```
index_generator:
  path: '/blog'
```

section to my config file to make it work (which it did!). However this should really be in the documentation or even the default `_config.yml` since it must be a pretty normal use case? Can we add it? Thank you for a great product!

**Comment by NoahDragon** [comment]
Thank you for point this out. Sure I will put this into the default config file. Add the original issue for reference: https://github.com/hexojs/hexo/issues/2645

**Comment by NoahDragon** [comment]
I have added the default setting to the config file, please have a look. https://github.com/hexojs/hexo-starter/blob/master/_config.yml#L46-L53

**Comment by johot** [comment]
Nice @NoahDragon! Would be nice to see it in the docs for the official webpage in the future also :+1: !

**Comment by curbengh** [comment]
btw, you could also
```
archive_dir: blog
```
to replace 'archives' page with '/blog'.

**Comment by YoshinoriN** [comment]
@johot 
Thank you for your advice :)
We added the documentation.
