### ISSUE TITLE
some posts don't show on the home page

### ISSUE THREAD

**Issue by chenfengkg** [hexojs/hexo-generator-index#14]
for some reasons ,I need to hide some post,I do the procedure as follow:

1. change he them/next/laytout/index.swig to like this:
 `<section id="posts" class="posts-expand">
    {% for post in page.posts %}
    	{% if post.visible !== 'hide'%}
      	{{ post_template.render(post, true) }}
    	{% endif %}
    {% endfor %}
  </section>`
as it  shows , I add a judgement to make  it don't render the post when I set the post's attribute visible to  hide.

then it show error!

it divide posts before redering  which make  the number of post in some page fewer than other pages.

you can visite my blog http://chenfengkg.cn.

my slution is to make redering post be first ,then  divide page.so this can slove this problem.but  I don't know how to change your code ,can you help me .or do you have any other solution? Thanks in advance.

**Comment by stevenjoezhang** [comment]
To hide some posts in home page:

https://github.com/stevenjoezhang/hexo-generator-indexed/blob/9fc4c10772ef591112662035d0dd7de30ba7a38c/lib/generator.js#L9-L21
