### ISSUE TITLE
Add sorting option

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo-generator-index#2]
The sorting is hardcoded as 
```sh
var posts = locals.posts.sort('-date');
```

Can it be made into `hexo.config`?

**Comment by iissnan** [comment]
+1

**Comment by iissnan** [comment]
I have created a pull request for this issue (#3).

Recently, I am working on adding sticky posts feature for theme [NexT](https://github.com/iissnan/hexo-theme-next). My solution is to add a Front-matter, let's say `sticky` and resort posts via comparing this value when displaying in templates.  Unfortunately, I found there was no chances to do the resort after this generator ran.

Although there is another solution, but I think change order in this way is more straightforward. It is also helpful for other theme developers and users.

Thanks,
Vi

**Comment by leesei** [comment]
Merged and pending publish.
Thanks.
