### ISSUE TITLE
readme is unclear, what kind of index is this generating?

### ISSUE THREAD

**Issue by handylearn** [hexojs/hexo-generator-index#4]
The word 'index' is used very often with different meanings. What does this plugin actually do? Does it generates complete pages or strings, or what, and based on what? And how to access the result?

**Comment by mnlbox** [comment]
I have same question.
@NoahDragon you suggest me to remove unused Hexo plugin in [this issue](https://github.com/hexojs/hexo/issues/2579).
I saw this plugin in my `package.json` and don't know is it necessary or we can remove this?

**Comment by NoahDragon** [comment]
This generates the index or archive page. If you need those two pages in your website, I suggest to keep them. @mnlbox

**Comment by mnlbox** [comment]
@NoahDragon  I remove archive plugin from my project. What is Index page? Is it different from root URL?
