### ISSUE TITLE
First page url incorrect

### ISSUE THREAD

**Issue by Haocen** [hexojs/hexo-generator-index#5]
I've got following configuration in my _config.yml

> url: http://website.com/child
> root: /child/
> 
>   index_generator:
>   per_page: 10

And the link to first page will always take me to http://website.com , instead of https://website.com/child

This problem cannot be reproduced on Hexo server, because it always redirect http://localhost:4000/ to http://localhost:4000/child

it seemed in:

> hexo-pagination/lib/pagination.js

Some special handling is needed for the first page. But I cannot find where since I'm not familiar with Hexo.

**Comment by bananapple** [comment]
I have same problem, also my CSS link is incorrect.

**Comment by bananapple** [comment]
I've fixed the problem, it is not a bug or issue.
I created another repo called blog, install Hexo in this repo, and deploy it by the certain branch called "gh-pages"

for reference
here's my _config.yml
`#URL
url: http://yourUserName.github.io/blog/
root: /blog/`
`#Deployment
deploy:
  type: git
  repo: git@github.com:yourUserName/blog.git
  branch: gh-pages
`
I am new to GitHub pages ...  👶
