### ISSUE TITLE
Feature Request: Hide posts from the index

### ISSUE THREAD

**Issue by zhang-stephen** [hexojs/hexo-generator-index#88]
Is it possible to add an option, e.g. `hidden: true`, into front matter, and to remove this post from the index page?

**Comment by SukkaW** [comment]
@zhang-stephen 

Currently, the `hexo-generator-index` doesn't have such an option, but hexo themes can implement this very easily! Here is an example with `.ejs`:

```ejs
<!-- Post List -->
<% page.posts.each((post) => { %>
  <!-- Post Entry -->
  <%- partial('_partial/post-entry', { post }) %>
<% }); %>
```

```diff
<!-- Post List -->
<% page.posts.each((post) => { %>
  <!-- Post Entry -->
+ <% if (post.hidden !== true) { %>
  <%- partial('_partial/post-entry', { post }) %>
+ <% } %>
<% }); %>
```
